# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import compservice_pb2 as compservice__pb2


class compserviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.downloadModel = channel.unary_unary(
                '/compservice/downloadModel',
                request_serializer=compservice__pb2.Model.SerializeToString,
                response_deserializer=compservice__pb2.Response.FromString,
                )
        self.deleteModel = channel.unary_unary(
                '/compservice/deleteModel',
                request_serializer=compservice__pb2.Model.SerializeToString,
                response_deserializer=compservice__pb2.Response.FromString,
                )
        self.getModels = channel.unary_unary(
                '/compservice/getModels',
                request_serializer=compservice__pb2.Empty.SerializeToString,
                response_deserializer=compservice__pb2.ModelList.FromString,
                )
        self.downloadStatic = channel.unary_unary(
                '/compservice/downloadStatic',
                request_serializer=compservice__pb2.Model.SerializeToString,
                response_deserializer=compservice__pb2.Response.FromString,
                )
        self.deleteStatic = channel.unary_unary(
                '/compservice/deleteStatic',
                request_serializer=compservice__pb2.Model.SerializeToString,
                response_deserializer=compservice__pb2.Response.FromString,
                )
        self.getStaticModels = channel.unary_unary(
                '/compservice/getStaticModels',
                request_serializer=compservice__pb2.Empty.SerializeToString,
                response_deserializer=compservice__pb2.ModelStaticList.FromString,
                )
        self.inf_session = channel.unary_stream(
                '/compservice/inf_session',
                request_serializer=compservice__pb2.Session.SerializeToString,
                response_deserializer=compservice__pb2.EmbeddingDataSet.FromString,
                )
        self.getDevices = channel.unary_unary(
                '/compservice/getDevices',
                request_serializer=compservice__pb2.Empty.SerializeToString,
                response_deserializer=compservice__pb2.DeviceList.FromString,
                )


class compserviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def downloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def downloadStatic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteStatic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStaticModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def inf_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_compserviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'downloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.downloadModel,
                    request_deserializer=compservice__pb2.Model.FromString,
                    response_serializer=compservice__pb2.Response.SerializeToString,
            ),
            'deleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteModel,
                    request_deserializer=compservice__pb2.Model.FromString,
                    response_serializer=compservice__pb2.Response.SerializeToString,
            ),
            'getModels': grpc.unary_unary_rpc_method_handler(
                    servicer.getModels,
                    request_deserializer=compservice__pb2.Empty.FromString,
                    response_serializer=compservice__pb2.ModelList.SerializeToString,
            ),
            'downloadStatic': grpc.unary_unary_rpc_method_handler(
                    servicer.downloadStatic,
                    request_deserializer=compservice__pb2.Model.FromString,
                    response_serializer=compservice__pb2.Response.SerializeToString,
            ),
            'deleteStatic': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteStatic,
                    request_deserializer=compservice__pb2.Model.FromString,
                    response_serializer=compservice__pb2.Response.SerializeToString,
            ),
            'getStaticModels': grpc.unary_unary_rpc_method_handler(
                    servicer.getStaticModels,
                    request_deserializer=compservice__pb2.Empty.FromString,
                    response_serializer=compservice__pb2.ModelStaticList.SerializeToString,
            ),
            'inf_session': grpc.unary_stream_rpc_method_handler(
                    servicer.inf_session,
                    request_deserializer=compservice__pb2.Session.FromString,
                    response_serializer=compservice__pb2.EmbeddingDataSet.SerializeToString,
            ),
            'getDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.getDevices,
                    request_deserializer=compservice__pb2.Empty.FromString,
                    response_serializer=compservice__pb2.DeviceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compservice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class compservice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def downloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/downloadModel',
            compservice__pb2.Model.SerializeToString,
            compservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/deleteModel',
            compservice__pb2.Model.SerializeToString,
            compservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/getModels',
            compservice__pb2.Empty.SerializeToString,
            compservice__pb2.ModelList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def downloadStatic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/downloadStatic',
            compservice__pb2.Model.SerializeToString,
            compservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteStatic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/deleteStatic',
            compservice__pb2.Model.SerializeToString,
            compservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getStaticModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/getStaticModels',
            compservice__pb2.Empty.SerializeToString,
            compservice__pb2.ModelStaticList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def inf_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/compservice/inf_session',
            compservice__pb2.Session.SerializeToString,
            compservice__pb2.EmbeddingDataSet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compservice/getDevices',
            compservice__pb2.Empty.SerializeToString,
            compservice__pb2.DeviceList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
