# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63ompservice.proto\"\x1b\n\x08Progress\x12\x0f\n\x07percent\x18\x01 \x01(\x05\"\x1d\n\x08Response\x12\x11\n\tcompleted\x18\x01 \x01(\x08\"\x16\n\x05Model\x12\r\n\x05\x64ummy\x18\x01 \x01(\x05\"\x1b\n\tModelList\x12\x0e\n\x06\x64ummy2\x18\x01 \x01(\x05\"\x19\n\x07\x44\x61taset\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x1d\n\x0b\x44\x61tasetList\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x1d\n\x0b\x44\x61tasetName\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x1f\n\rEmbeddingData\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x19\n\x07Session\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x17\n\x05\x44ummy\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\"\x1c\n\nDeviceInfo\x12\x0e\n\x06\x64ummy3\x18\x01 \x01(\x05\x32\xcd\x02\n\x0b\x63ompservice\x12&\n\rdownloadModel\x12\x06.Model\x1a\t.Progress\"\x00\x30\x01\x12\"\n\x0b\x64\x65leteModel\x12\x06.Model\x1a\t.Response\"\x00\x12!\n\tgetModels\x12\x06.Dummy\x1a\n.ModelList\"\x00\x12)\n\x0eupdloadDataset\x12\x08.Dataset\x1a\t.Response\"\x00(\x01\x12*\n\rdeleteDataset\x12\x0c.DatasetName\x1a\t.Response\"\x00\x12&\n\x0c\x64getDatasets\x12\x06.Dummy\x1a\x0c.DatasetList\"\x00\x12+\n\x0binf_session\x12\x08.Session\x1a\x0e.EmbeddingData\"\x00\x30\x01\x12#\n\ngetDevices\x12\x06.Dummy\x1a\x0b.DeviceInfo\"\x00\x62\x06proto3'
)




_PROGRESS = _descriptor.Descriptor(
  name='Progress',
  full_name='Progress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='percent', full_name='Progress.percent', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='completed', full_name='Response.completed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=79,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy', full_name='Model.dummy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=103,
)


_MODELLIST = _descriptor.Descriptor(
  name='ModelList',
  full_name='ModelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy2', full_name='ModelList.dummy2', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=132,
)


_DATASET = _descriptor.Descriptor(
  name='Dataset',
  full_name='Dataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='Dataset.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=159,
)


_DATASETLIST = _descriptor.Descriptor(
  name='DatasetList',
  full_name='DatasetList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='DatasetList.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=190,
)


_DATASETNAME = _descriptor.Descriptor(
  name='DatasetName',
  full_name='DatasetName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='DatasetName.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=221,
)


_EMBEDDINGDATA = _descriptor.Descriptor(
  name='EmbeddingData',
  full_name='EmbeddingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='EmbeddingData.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=254,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='Session.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=281,
)


_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='Dummy.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=306,
)


_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy3', full_name='DeviceInfo.dummy3', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=336,
)

DESCRIPTOR.message_types_by_name['Progress'] = _PROGRESS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['ModelList'] = _MODELLIST
DESCRIPTOR.message_types_by_name['Dataset'] = _DATASET
DESCRIPTOR.message_types_by_name['DatasetList'] = _DATASETLIST
DESCRIPTOR.message_types_by_name['DatasetName'] = _DATASETNAME
DESCRIPTOR.message_types_by_name['EmbeddingData'] = _EMBEDDINGDATA
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Progress = _reflection.GeneratedProtocolMessageType('Progress', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESS,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Progress)
  })
_sym_db.RegisterMessage(Progress)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

ModelList = _reflection.GeneratedProtocolMessageType('ModelList', (_message.Message,), {
  'DESCRIPTOR' : _MODELLIST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:ModelList)
  })
_sym_db.RegisterMessage(ModelList)

Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), {
  'DESCRIPTOR' : _DATASET,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Dataset)
  })
_sym_db.RegisterMessage(Dataset)

DatasetList = _reflection.GeneratedProtocolMessageType('DatasetList', (_message.Message,), {
  'DESCRIPTOR' : _DATASETLIST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:DatasetList)
  })
_sym_db.RegisterMessage(DatasetList)

DatasetName = _reflection.GeneratedProtocolMessageType('DatasetName', (_message.Message,), {
  'DESCRIPTOR' : _DATASETNAME,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:DatasetName)
  })
_sym_db.RegisterMessage(DatasetName)

EmbeddingData = _reflection.GeneratedProtocolMessageType('EmbeddingData', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGDATA,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingData)
  })
_sym_db.RegisterMessage(EmbeddingData)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Session)
  })
_sym_db.RegisterMessage(Session)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), {
  'DESCRIPTOR' : _DUMMY,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Dummy)
  })
_sym_db.RegisterMessage(Dummy)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFO,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:DeviceInfo)
  })
_sym_db.RegisterMessage(DeviceInfo)



_COMPSERVICE = _descriptor.ServiceDescriptor(
  name='compservice',
  full_name='compservice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=339,
  serialized_end=672,
  methods=[
  _descriptor.MethodDescriptor(
    name='downloadModel',
    full_name='compservice.downloadModel',
    index=0,
    containing_service=None,
    input_type=_MODEL,
    output_type=_PROGRESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteModel',
    full_name='compservice.deleteModel',
    index=1,
    containing_service=None,
    input_type=_MODEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getModels',
    full_name='compservice.getModels',
    index=2,
    containing_service=None,
    input_type=_DUMMY,
    output_type=_MODELLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updloadDataset',
    full_name='compservice.updloadDataset',
    index=3,
    containing_service=None,
    input_type=_DATASET,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteDataset',
    full_name='compservice.deleteDataset',
    index=4,
    containing_service=None,
    input_type=_DATASETNAME,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='dgetDatasets',
    full_name='compservice.dgetDatasets',
    index=5,
    containing_service=None,
    input_type=_DUMMY,
    output_type=_DATASETLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='inf_session',
    full_name='compservice.inf_session',
    index=6,
    containing_service=None,
    input_type=_SESSION,
    output_type=_EMBEDDINGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getDevices',
    full_name='compservice.getDevices',
    index=7,
    containing_service=None,
    input_type=_DUMMY,
    output_type=_DEVICEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPSERVICE)

DESCRIPTOR.services_by_name['compservice'] = _COMPSERVICE

# @@protoc_insertion_point(module_scope)
