# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63ompservice.proto\"\x1d\n\x08Response\x12\x11\n\tcompleted\x18\x01 \x01(\x08\"\x1a\n\x05Model\x12\x11\n\tmodelname\x18\x01 \x01(\t\"(\n\tModelList\x12\x1b\n\x05model\x18\x01 \x03(\x0b\x32\x0c.ModelStruct\"4\n\x0fModelStaticList\x12!\n\x05model\x18\x01 \x03(\x0b\x32\x12.ModelStaticStruct\"9\n\x0bModelStruct\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06layers\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\"!\n\x11ModelStaticStruct\x12\x0c\n\x04name\x18\x01 \x01(\t\"^\n\x10\x45mbeddingDataSet\x12.\n\tembedding\x18\x01 \x03(\x0b\x32\x1b.EmbeddingDataSet.Embedding\x1a\x1a\n\tEmbedding\x12\r\n\x05value\x18\x01 \x03(\x02\"$\n\x07Session\x12\x19\n\x07request\x18\x01 \x03(\x0b\x32\x08.Request\"\x94\x01\n\x07Request\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tlayer_low\x18\x02 \x01(\x05\x12\x10\n\x08layer_up\x18\x03 \x01(\x05\x12\x11\n\tcomp_func\x18\x04 \x01(\t\x12\x10\n\x08sentence\x18\x05 \x03(\t\x12\x11\n\tbatchsize\x18\x06 \x01(\x05\x12\x1d\n\x07\x64\x65vices\x18\x07 \x01(\x0b\x32\x0c.DeviceNames\"\x83\x01\n\nDeviceList\x12\x1f\n\x03\x64\x65v\x18\x01 \x03(\x0b\x32\x12.DeviceList.Device\x1aT\n\x06\x44\x65vice\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x14\n\x0cmemory_total\x18\x03 \x01(\x05\x12\x13\n\x0bmemory_free\x18\x04 \x01(\x05\"\x1b\n\x0b\x44\x65viceNames\x12\x0c\n\x04name\x18\x01 \x03(\t\"\x16\n\x05\x45mpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\x32\xca\x02\n\x0b\x63ompservice\x12$\n\rdownloadModel\x12\x06.Model\x1a\t.Response\"\x00\x12\"\n\x0b\x64\x65leteModel\x12\x06.Model\x1a\t.Response\"\x00\x12!\n\tgetModels\x12\x06.Empty\x1a\n.ModelList\"\x00\x12%\n\x0e\x64ownloadStatic\x12\x06.Model\x1a\t.Response\"\x00\x12#\n\x0c\x64\x65leteStatic\x12\x06.Model\x1a\t.Response\"\x00\x12-\n\x0fgetStaticModels\x12\x06.Empty\x1a\x10.ModelStaticList\"\x00\x12.\n\x0binf_session\x12\x08.Session\x1a\x11.EmbeddingDataSet\"\x00\x30\x01\x12#\n\ngetDevices\x12\x06.Empty\x1a\x0b.DeviceList\"\x00\x62\x06proto3'
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='completed', full_name='Response.completed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelname', full_name='Model.modelname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=78,
)


_MODELLIST = _descriptor.Descriptor(
  name='ModelList',
  full_name='ModelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='ModelList.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=120,
)


_MODELSTATICLIST = _descriptor.Descriptor(
  name='ModelStaticList',
  full_name='ModelStaticList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='ModelStaticList.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=174,
)


_MODELSTRUCT = _descriptor.Descriptor(
  name='ModelStruct',
  full_name='ModelStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ModelStruct.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layers', full_name='ModelStruct.layers', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='ModelStruct.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=233,
)


_MODELSTATICSTRUCT = _descriptor.Descriptor(
  name='ModelStaticStruct',
  full_name='ModelStaticStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ModelStaticStruct.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=268,
)


_EMBEDDINGDATASET_EMBEDDING = _descriptor.Descriptor(
  name='Embedding',
  full_name='EmbeddingDataSet.Embedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='EmbeddingDataSet.Embedding.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=364,
)

_EMBEDDINGDATASET = _descriptor.Descriptor(
  name='EmbeddingDataSet',
  full_name='EmbeddingDataSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='EmbeddingDataSet.embedding', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EMBEDDINGDATASET_EMBEDDING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=364,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='Session.request', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=402,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Request.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layer_low', full_name='Request.layer_low', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layer_up', full_name='Request.layer_up', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comp_func', full_name='Request.comp_func', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sentence', full_name='Request.sentence', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchsize', full_name='Request.batchsize', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='devices', full_name='Request.devices', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=553,
)


_DEVICELIST_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='DeviceList.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='DeviceList.Device.device_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='DeviceList.Device.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory_total', full_name='DeviceList.Device.memory_total', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memory_free', full_name='DeviceList.Device.memory_free', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=687,
)

_DEVICELIST = _descriptor.Descriptor(
  name='DeviceList',
  full_name='DeviceList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dev', full_name='DeviceList.dev', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICELIST_DEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=687,
)


_DEVICENAMES = _descriptor.Descriptor(
  name='DeviceNames',
  full_name='DeviceNames',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DeviceNames.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=716,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='Empty.empty', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=740,
)

_MODELLIST.fields_by_name['model'].message_type = _MODELSTRUCT
_MODELSTATICLIST.fields_by_name['model'].message_type = _MODELSTATICSTRUCT
_EMBEDDINGDATASET_EMBEDDING.containing_type = _EMBEDDINGDATASET
_EMBEDDINGDATASET.fields_by_name['embedding'].message_type = _EMBEDDINGDATASET_EMBEDDING
_SESSION.fields_by_name['request'].message_type = _REQUEST
_REQUEST.fields_by_name['devices'].message_type = _DEVICENAMES
_DEVICELIST_DEVICE.containing_type = _DEVICELIST
_DEVICELIST.fields_by_name['dev'].message_type = _DEVICELIST_DEVICE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['ModelList'] = _MODELLIST
DESCRIPTOR.message_types_by_name['ModelStaticList'] = _MODELSTATICLIST
DESCRIPTOR.message_types_by_name['ModelStruct'] = _MODELSTRUCT
DESCRIPTOR.message_types_by_name['ModelStaticStruct'] = _MODELSTATICSTRUCT
DESCRIPTOR.message_types_by_name['EmbeddingDataSet'] = _EMBEDDINGDATASET
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['DeviceList'] = _DEVICELIST
DESCRIPTOR.message_types_by_name['DeviceNames'] = _DEVICENAMES
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

ModelList = _reflection.GeneratedProtocolMessageType('ModelList', (_message.Message,), {
  'DESCRIPTOR' : _MODELLIST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:ModelList)
  })
_sym_db.RegisterMessage(ModelList)

ModelStaticList = _reflection.GeneratedProtocolMessageType('ModelStaticList', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTATICLIST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:ModelStaticList)
  })
_sym_db.RegisterMessage(ModelStaticList)

ModelStruct = _reflection.GeneratedProtocolMessageType('ModelStruct', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTRUCT,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:ModelStruct)
  })
_sym_db.RegisterMessage(ModelStruct)

ModelStaticStruct = _reflection.GeneratedProtocolMessageType('ModelStaticStruct', (_message.Message,), {
  'DESCRIPTOR' : _MODELSTATICSTRUCT,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:ModelStaticStruct)
  })
_sym_db.RegisterMessage(ModelStaticStruct)

EmbeddingDataSet = _reflection.GeneratedProtocolMessageType('EmbeddingDataSet', (_message.Message,), {

  'Embedding' : _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), {
    'DESCRIPTOR' : _EMBEDDINGDATASET_EMBEDDING,
    '__module__' : 'compservice_pb2'
    # @@protoc_insertion_point(class_scope:EmbeddingDataSet.Embedding)
    })
  ,
  'DESCRIPTOR' : _EMBEDDINGDATASET,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:EmbeddingDataSet)
  })
_sym_db.RegisterMessage(EmbeddingDataSet)
_sym_db.RegisterMessage(EmbeddingDataSet.Embedding)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Session)
  })
_sym_db.RegisterMessage(Session)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

DeviceList = _reflection.GeneratedProtocolMessageType('DeviceList', (_message.Message,), {

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
    'DESCRIPTOR' : _DEVICELIST_DEVICE,
    '__module__' : 'compservice_pb2'
    # @@protoc_insertion_point(class_scope:DeviceList.Device)
    })
  ,
  'DESCRIPTOR' : _DEVICELIST,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:DeviceList)
  })
_sym_db.RegisterMessage(DeviceList)
_sym_db.RegisterMessage(DeviceList.Device)

DeviceNames = _reflection.GeneratedProtocolMessageType('DeviceNames', (_message.Message,), {
  'DESCRIPTOR' : _DEVICENAMES,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:DeviceNames)
  })
_sym_db.RegisterMessage(DeviceNames)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'compservice_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_COMPSERVICE = _descriptor.ServiceDescriptor(
  name='compservice',
  full_name='compservice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=743,
  serialized_end=1073,
  methods=[
  _descriptor.MethodDescriptor(
    name='downloadModel',
    full_name='compservice.downloadModel',
    index=0,
    containing_service=None,
    input_type=_MODEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteModel',
    full_name='compservice.deleteModel',
    index=1,
    containing_service=None,
    input_type=_MODEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getModels',
    full_name='compservice.getModels',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MODELLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='downloadStatic',
    full_name='compservice.downloadStatic',
    index=3,
    containing_service=None,
    input_type=_MODEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteStatic',
    full_name='compservice.deleteStatic',
    index=4,
    containing_service=None,
    input_type=_MODEL,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getStaticModels',
    full_name='compservice.getStaticModels',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MODELSTATICLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='inf_session',
    full_name='compservice.inf_session',
    index=6,
    containing_service=None,
    input_type=_SESSION,
    output_type=_EMBEDDINGDATASET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getDevices',
    full_name='compservice.getDevices',
    index=7,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DEVICELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPSERVICE)

DESCRIPTOR.services_by_name['compservice'] = _COMPSERVICE

# @@protoc_insertion_point(module_scope)
